name: Automatic Commit and Push

on:
  push:
    branches:
      - master  # Puoi specificare un altro ramo, se necessario
  pull_request:
    branches:
      - master  # Può essere utile anche per i pull request

jobs:
  push_changes:
    runs-on: ubuntu-latest  # Usa il runner su Ubuntu

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Fa il checkout del repository

    - name: Set up Python (se il tuo progetto è Python)
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Commit changes
      run: |
        git config --global user.name "ratzar"  # Sostituisci con il tuo nome GitHub
        git config --global user.email "ingrametti@gmail.com"  # Sostituisci con la tua email
        git add .  # Aggiungi tutte le modifiche
        git commit -m "Commit automatico via GitHub Actions"  # Messaggio di commit
        git push origin master  # Fai il push delle modifiche

    - name: Push changes to GitHub
      run: git push origin master  # Fai il push finale al tuo repository remoto
