name: Code Quality Check

on:
  push:
    branches:
      - master  # Esegui su push nella branch master
  pull_request:
    branches:
      - master  # Esegui anche sui pull request

jobs:
  lint_and_test:
    runs-on: ubuntu-latest  # Usa l'ambiente di esecuzione Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Checkout del repository

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 mypy bandit pytest  # Installa gli strumenti di analisi e testing

      - name: Run Flake8 (Code style)
        run: |
          flake8 src  # Esegui il controllo dello stile sul codice sorgente

      - name: Run MyPy (Type checking)
        run: |
          mypy src  # Esegui il controllo dei tipi

      - name: Run Bandit (Security check)
        run: |
          bandit -r src  # Esegui il controllo di sicurezza

      - name: Run Pytest (Testing)
        run: |
          pytest  # Esegui i test
